// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BE_mHealthBank.Models
{
    public partial class TblUser
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string AddressName { get; set; }
        public DateTime? BirthDate { get; set; }
        public string Gender { get; set; }
        public string ImageProfile { get; set; }
    }
}